"""add events table

Revision ID: 383673a3ff2e
Revises: add_events_table
Create Date: 2025-07-05 21:17:31.706285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '383673a3ff2e'
down_revision: Union[str, None] = '4c11619cb743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
        sa.Column('event_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('country', sa.String(length=100), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=False),
        sa.Column('initial_budget', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('travel_expenses', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0.00'),
        sa.Column('end_budget', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0.00'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=False)
    
    op.add_column('products', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_products_event_id', 'products', 'events', ['event_id'], ['event_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_products_event_id', 'products', type_='foreignkey')
    op.drop_column('products', 'event_id')
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
