"""Add cascade delete to product relationships

Revision ID: 458dd1e193ba
Revises: 83082b7bef86
Create Date: 2025-06-30 21:34:20.964795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '458dd1e193ba'
down_revision: Union[str, None] = '83082b7bef86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inventory_product_id_fkey', 'inventory', type_='foreignkey')
    op.create_foreign_key(None, 'inventory', 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.drop_constraint('order_items_product_id_fkey', 'order_items', type_='foreignkey')
    op.drop_constraint('order_items_order_id_fkey', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['order_id'], ondelete='CASCADE')
    op.drop_constraint('price_history_product_id_fkey', 'price_history', type_='foreignkey')
    op.create_foreign_key(None, 'price_history', 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.drop_constraint('price_points_product_id_fkey', 'price_points', type_='foreignkey')
    op.create_foreign_key(None, 'price_points', 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.drop_constraint('product_images_product_id_fkey', 'product_images', type_='foreignkey')
    op.create_foreign_key(None, 'product_images', 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.drop_constraint('product_instances_product_id_fkey', 'product_instances', type_='foreignkey')
    op.create_foreign_key(None, 'product_instances', 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.drop_constraint('products_category_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'product_categories', ['category_id'], ['category_id'], ondelete='SET NULL')
    op.drop_constraint('supplier_products_supplier_id_fkey', 'supplier_products', type_='foreignkey')
    op.drop_constraint('supplier_products_product_id_fkey', 'supplier_products', type_='foreignkey')
    op.create_foreign_key(None, 'supplier_products', 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'supplier_products', 'suppliers', ['supplier_id'], ['supplier_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supplier_products', type_='foreignkey')
    op.drop_constraint(None, 'supplier_products', type_='foreignkey')
    op.create_foreign_key('supplier_products_product_id_fkey', 'supplier_products', 'products', ['product_id'], ['product_id'])
    op.create_foreign_key('supplier_products_supplier_id_fkey', 'supplier_products', 'suppliers', ['supplier_id'], ['supplier_id'])
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_category_id_fkey', 'products', 'product_categories', ['category_id'], ['category_id'])
    op.drop_constraint(None, 'product_instances', type_='foreignkey')
    op.create_foreign_key('product_instances_product_id_fkey', 'product_instances', 'products', ['product_id'], ['product_id'])
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.create_foreign_key('product_images_product_id_fkey', 'product_images', 'products', ['product_id'], ['product_id'])
    op.drop_constraint(None, 'price_points', type_='foreignkey')
    op.create_foreign_key('price_points_product_id_fkey', 'price_points', 'products', ['product_id'], ['product_id'])
    op.drop_constraint(None, 'price_history', type_='foreignkey')
    op.create_foreign_key('price_history_product_id_fkey', 'price_history', 'products', ['product_id'], ['product_id'])
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_order_id_fkey', 'order_items', 'orders', ['order_id'], ['order_id'])
    op.create_foreign_key('order_items_product_id_fkey', 'order_items', 'products', ['product_id'], ['product_id'])
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.create_foreign_key('inventory_product_id_fkey', 'inventory', 'products', ['product_id'], ['product_id'])
    # ### end Alembic commands ###
