"""Add cascade delete to sales.product_id

Revision ID: 4c11619cb743
Revises: 458dd1e193ba
Create Date: 2025-06-30 21:36:31.509681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c11619cb743'
down_revision: Union[str, None] = '458dd1e193ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sales_product_id_fkey', 'sales', type_='foreignkey')
    op.create_foreign_key(None, 'sales', 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.create_foreign_key('sales_product_id_fkey', 'sales', 'products', ['product_id'], ['product_id'])
    # ### end Alembic commands ###
