""""Add_ProductInstance_model"

Revision ID: 83082b7bef86
Revises: 89e961d109d2
Create Date: 2025-06-29 23:38:34.954243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83082b7bef86'
down_revision: Union[str, None] = '89e961d109d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_instances',
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('base_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('instance_id')
    )
    op.create_index(op.f('ix_product_instances_instance_id'), 'product_instances', ['instance_id'], unique=False)
    op.create_index(op.f('ix_profit_and_loss_pnl_id'), 'profit_and_loss', ['pnl_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profit_and_loss_pnl_id'), table_name='profit_and_loss')
    op.drop_index(op.f('ix_product_instances_instance_id'), table_name='product_instances')
    op.drop_table('product_instances')
    # ### end Alembic commands ###
