"""add default condition to product instances

Revision ID: 83738e4b524c
Revises: b8d01733d606
Create Date: 2025-08-04 12:27:27.327663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83738e4b524c'
down_revision: Union[str, None] = 'b8d01733d606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_instances', sa.Column('condition', sa.String(length=50), nullable=True))
    op.alter_column('product_instances', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_instances', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # op.drop_constraint('fk_product_instances_product_id', 'product_instances', type_='foreignkey')
    op.create_foreign_key('fk_product_instances_product_id', 'product_instances', 'products', ['product_id'], ['product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_product_instances_product_id', 'product_instances', type_='foreignkey')
    op.create_foreign_key('product_instances_product_id_fkey', 'product_instances', 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.alter_column('product_instances', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_instances', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('product_instances', 'condition')
    # ### end Alembic commands ###
