"""add_travel_expenses_table_and_remove_travel_expenses_from_events

Revision ID: b8d01733d606
Revises: 383673a3ff2e
Create Date: 2025-07-05 23:19:25.138579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d01733d606'
down_revision: Union[str, None] = '383673a3ff2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_expenses',
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('receipt_data', sa.LargeBinary(), nullable=True),
    sa.Column('receipt_type', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('expense_id')
    )
    op.create_index(op.f('ix_travel_expenses_expense_id'), 'travel_expenses', ['expense_id'], unique=False)
    op.drop_column('events', 'travel_expenses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('travel_expenses', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_travel_expenses_expense_id'), table_name='travel_expenses')
    op.drop_table('travel_expenses')
    # ### end Alembic commands ###
